---
# https://grafana.com/docs/loki/latest/clients/promtail/configuration/
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: containers
    # https://grafana.com/docs/loki/latest/clients/promtail/configuration/#docker_sd_config
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 15s
        filters:
          - name: label
            values: ["io.github.agebhar1.project=observability"]
    relabel_configs:
      - source_labels: ["__meta_docker_container_label_com_docker_compose_service"]
        target_label: "service"
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: "container"
      - source_labels: ["__meta_docker_container_label_hostname"]
        target_label: "hostname"
    pipeline_stages:
      - docker: {}
      - static_labels:
          job: containers

  - job_name: journal
    # https://grafana.com/docs/loki/latest/clients/promtail/configuration/#journal
    # https://grafana.com/docs/loki/latest/clients/promtail/scraping/#journal-scraping-linux-only
    # man systemd.journal-fields
    journal:
      path: /var/log/journal
      labels:
        job: journal
    relabel_configs:
      - source_labels: ["__journal_priority_keyword"]
        target_label: "level"
      - source_labels: ["__journal_syslog_identifier"]
        target_label: "syslog_identifier"
      - source_labels: ["__journal__systemd_cgroup"]
        target_label: "systemd_cgroup"
      - source_labels: ["__journal__systemd_slice"]
        target_label: "systemd_slice"
      - source_labels: ["__journal__systemd_unit"]
        target_label: "systemd_unit"
      - source_labels: ["__journal__systemd_user_unit"]
        target_label: "systemd_user_unit"
      - source_labels: ["__journal__systemd_user_slice"]
        target_label: "systemd_user_slice"
      - source_labels: ["__journal__systemd_session"]
        target_label: "systemd_session"
      - source_labels: ["__journal__systemd_owner_uid"]
        target_label: "systemd_owner_uid"
      - source_labels: ["__journal__selinux_context"]
        target_label: "selinux_context"
      - source_labels: ["__journal__audit_session"]
        target_label: "audit_session"
      - source_labels: ["__journal__audit_loginuid"]
        target_label: "audit_loginuid"
      - source_labels: ["__journal__hostname"]
        target_label: "hostname"
    pipeline_stages:
      - structured_metadata:
          level:
          systemd_cgroup:
          systemd_slice:
          systemd_unit:
          systemd_user_unit:
          systemd_user_slice:
          systemd_session:
          systemd_owner_uid:
          selinux_context:
          audit_session:
          audit_loginuid:
      - labeldrop:
          - level
          - systemd_cgroup
          - systemd_slice
          - systemd_unit
          - systemd_user_unit
          - systemd_user_slice
          - systemd_session
          - systemd_owner_uid
          - selinux_context
          - audit_session
          - audit_loginuid

  - job_name: various-metrics
    # https://grafana.com/docs/loki/latest/clients/promtail/configuration/#static_configs
    static_configs:
      - labels:
          job: various
          __path__: /mnt/log/*.log
          __path_exclude__: /mnt/log/structured-metadata-example.log
    pipeline_stages:
      # https://grafana.com/docs/loki/latest/clients/promtail/stages/metrics/
      - metrics:
          log_lines_total:
            type: Counter
            description: "total number of log lines"
            # prefix: promtail_custom_
            max_idle_duration: 24h
            config:
              match_all: true
              action: inc
          log_bytes_total:
            type: Counter
            description: "total bytes of log lines"
            # prefix: promtail_custom_
            max_idle_duration: 24h
            config:
              match_all: true
              count_entry_bytes: true
              action: add

  - job_name: structured-metadata
    # https://grafana.com/docs/loki/latest/clients/promtail/configuration/#static_configs
    static_configs:
      - labels:
          job: structured-metadata
          __path__: /mnt/log/structured-metadata-example.log
    pipeline_stages:
      - logfmt:
          mapping:
            stream:
            traceID:
      - replace:
          expression: "(traceID=[0-9a-c]+\\s?)"
      - labels:
          stream:
      - structured_metadata:
          traceID:
