---
apiVersion: 1

deleteDatasources:
  - name: Prometheus

datasources:
  # https://grafana.com/docs/grafana/latest/datasources/prometheus/
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: PBFA97CFB590B2093
