---
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "containers"
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 15s
        filters:
          - name: label
            values: ["io.github.agebhar1.project=observability"]
    relabel_configs:
      - source_labels: ["__meta_docker_container_label_io_prometheus_scrape"]
        regex: "true"
        action: keep
      - source_labels: ["__address__", "__meta_docker_container_label_io_prometheus_port"]
        regex: '(.+)(?::\d+);(\d+)'
        replacement: "$1:$2"
        target_label: "__address__"
      - source_labels: ["__meta_docker_container_label_io_prometheus_path"]
        regex: "((?:/[^/ ]+)+)"
        target_label: "__metrics_path__"
      - source_labels: ["__meta_docker_container_label_com_docker_compose_service"]
        target_label: "service"
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: "container"
      - source_labels: ["__meta_docker_container_label_hostname"]
        target_label: "instance"
