{
 "title": "Alloy Metrics Stage",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Log Byte Rate [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (filename) (rate(loki_process_custom_log_bytes_total{filename=~\".+\"}[1m]))",
     "legendFormat": "{{filename}}"
    }
   ]
  },
  {
   "title": "Log Lines Rate [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (filename) (rate(loki_process_custom_log_lines_total{filename=~\".+\"}[1m]))",
     "legendFormat": "{{filename}}"
    }
   ]
  },
  {
   "title": "/home/vagrant/alloy/log/",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"various\"}"
    }
   ]
  }
 ]
}