{
 "title": "Log Queries",
 "tags": [ "systemd" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "HTTP Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Status 200",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{app=~\"k6\"} |= \"status=200\""
    }
   ]
  },
  {
   "title": "HTTP Status 404",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{app=~\"k6\"} |~ \"status=404\""
    }
   ]
  },
  {
   "title": "HTTP Status 5xx",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{app=~\"k6\"} |~ \"status=5\""
    }
   ]
  },
  {
   "title": "POST requests w/ > 20KB",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{app=~\"k6\"} |= \"method=POST\" | logfmt | __error__ = \"\" | bytes > 20KB"
    }
   ]
  },
  { "title": "Systemd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "PAM Unix session opened",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "{job=\"systemd-journal\"}                                                # users invoked `sudo`\n    |~ `pam_unix\\([a-z]+:session\\)`\n    |= \"opened\"\n    | pattern \"pam_unix(<type>:session): session opened for user <_> by <user>(uid=<_>)\"\n    | __error__ = \"\"\n    | label_format type=\"{{.type}}\"\n    | line_format \"{{.user}}\""
    }
   ]
  },
  {
   "title": "Log",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "{job=\"systemd-journal\"}"
    }
   ]
  }
 ]
}