{
 "title": "Metric Queries",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\"k6\", format=\"logfmt\"}[$__interval] | logfmt)) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "HTTP Requests Bytes Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate({app=~\"k6\", format=\"logfmt\"}[$__interval] | logfmt | unwrap bytes)) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "PAM Unix sudo sessions opened",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(count_over_time(\n    {job=\"systemd-journal\"}[$__interval]\n        |~ `pam_unix\\(sudo:session\\)`\n        |= \"opened\"\n        | pattern \"pam_unix(sudo:session): session opened for user <_> by <user>(uid=<_>)\"\n        | __error__ = \"\"\n        | line_format \"{{.user}}\")) by (user)",
     "legendFormat": "{{user}}"
    }
   ]
  }
 ]
}