{
 "title": "PostgreSQL - Grafana DB",
 "description": "Grafana PostgreSQL metrics.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Rows",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "fetched",
     "expr": "sum(irate(pg_stat_database_tup_fetched{datname=\"grafana\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "fetched",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "fetched",
     "expr": "sum(irate(pg_stat_database_tup_returned{datname=\"grafana\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "returned",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "fetched",
     "expr": "sum(irate(pg_stat_database_tup_inserted{datname=\"grafana\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "inserted",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "fetched",
     "expr": "sum(irate(pg_stat_database_tup_updated{datname=\"grafana\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "updated",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "fetched",
     "expr": "sum(irate(pg_stat_database_tup_deleted{datname=\"grafana\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "deleted",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "QPS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_xact_commit{datname=\"grafana\"}[5m])) + sum(irate(pg_stat_database_xact_rollback{datname=\"grafana\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "xact_commit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Buffers Allocated",
     "expr": "irate(pg_stat_bgwriter_buffers_alloc[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "buffers_alloc",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "irate(pg_stat_bgwriter_buffers_backend_fsync[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "buffers_backend_fsync",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "irate(pg_stat_bgwriter_buffers_backend[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "buffers_backend",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "irate(pg_stat_bgwriter_buffers_clean[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "buffers_clean",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "irate(pg_stat_bgwriter_buffers_checkpoint[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "buffers_checkpoint",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "conflicts",
     "expr": "sum(rate(pg_stat_database_deadlocks{datname=\"grafana\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "deadlocks",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "conflicts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "alias": "deadlocks",
     "expr": "sum(rate(pg_stat_database_conflicts{datname=\"grafana\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "conflicts",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "deadlocks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cache hit ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_blks_hit{datname=\"grafana\"}) / (sum(pg_stat_database_blks_hit{datname=\"grafana\"}) + sum(pg_stat_database_blks_read{datname=\"grafana\"}))",
     "legendFormat": "cache hit rate"
    }
   ]
  },
  {
   "title": "Number of active connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=\"grafana\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}