{
 "title": "System Overview",
 "tags": [ "container" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service!=\"\"}[$__rate_interval])",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_compose_service!=\"\"}",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Container Logs",
   "type": "logs",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{job=\"containers\"}"
    }
   ]
  },
  { "title": "Grafana Loki", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Log Messages Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(loki_log_messages_total{instance=~\"loki.*\"}) by (level)",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Message Input Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "suffix:msg/s" } },
   "targets": [
    {
     "expr": "sum(irate(loki_log_messages_total[$__rate_interval])) by (level)",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Store Series / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum by (status) (rate(loki_store_series_total[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Bytes/Line p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_bytes_per_line_bucket[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki Cache Hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "targets": [
    { "expr": "loki_cache_hits", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Query Duration - Average",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile_over_time(0.50, {job=\"containers\", service=\"loki\"}\n    | logfmt\n    | __error__ = \"\"\n    | component=\"frontend\"\n    | query!=\"\"\n    | unwrap duration(duration) [$__range]) by (container)"
    }
   ]
  },
  {
   "title": "Query Duration - p95",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 7, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile_over_time(0.95, {job=\"containers\", service=\"loki\"}\n    | logfmt\n    | __error__ = \"\"\n    | component=\"frontend\"\n    | query!=\"\"\n    | unwrap duration(duration) [$__range]) by (container)"
    }
   ]
  },
  {
   "title": "Query Duration - p99",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile_over_time(0.99, {job=\"containers\", service=\"loki\"}\n    | logfmt\n    | __error__ = \"\"\n    | component=\"frontend\"\n    | query!=\"\"\n    | unwrap duration(duration) [$__range]) by (container)"
    }
   ]
  }
 ]
}